#!/bin/sh

# This file is sourced by Xsession(5), not executed.

# Make wasta applications visible to the user

# Migrate existing directory from old location
if [ ! -e "$HOME"/.local/share/wasta-user/applications \
    -a -e "$HOME"/.local/share/applications-wasta ]
then
	mv "$HOME"/.local/share/applications-wasta "$HOME"/.local/share/wasta-user/applications
fi

if [ -e "$HOME"/.local/share/wasta-system/applications ]
then
	XDG_DATA_DIRS=$HOME/.local/share/wasta-system:$XDG_DATA_DIRS
fi

if [ -e "$HOME"/.local/share/wasta-user/applications ]
then
	XDG_DATA_DIRS=$HOME/.local/share/wasta-user:$XDG_DATA_DIRS
fi
